### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by Ashiiidev**
_Please help in by merging my pull request_

### CODE REVIEW

**Comment by techoptimistyt** [comment]
Done

**Comment by Ashiiidev** [comment]
Thanks

**Comment by Ashiiidev** [comment]
Please provide me hacktoberfest -accepted tag it will be your pleasure

**Comment by Ashiiidev** [comment]
Can your please provide me hacktoberfest -accepted label i you it
necessary

**Comment by Ashiiidev** [comment]
As I think that my pr won't be counted for hacktoberfest without please
solve my doubt

**Pull request merged**
